global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 10.0
   publish_frequency: 10.0
   width: 6.0
   height: 6.0
   resolution: 0.02  #Based on jackal_race.yaml
   static_map: true
   rolling_window: false
